name: TestDeploy25
on: 
  push: 
    branches: [ main, qa, develop]
env: 
  URL_VAL: ${{ vars.ENV_TEST }}
  TEST: ${{ env.ENV_TEST }}
jobs:
  Deploy-environment-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Env variables"
        run: |
         echo "Value of variables is ${{ URL_VAL }} ..."
         echo "      of variables is  ${{ env.TEST }} ..."
         echo "second of variables is  $URL_VAL ..."
