name: TestDeploy25
on: 
  push: 
    branches: [ main, qa, develop]
env:
 env_var: ${{ VARS.TEST_ENV }}

jobs:
  Deploy-environment-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Env variables"
        run: |
         echo "Value of variables is $env_var ..."
         echo "      of variables is ${{ env.TEST_REP_VAR }} ..."
         echo "second of variables is ${{ env.TEST_VAR2 }} ..."
