name: TestDeploy
on: 
  push: 
    branches: [ develop, qa, main ] # develop
env:
  env_var: ${{ vars.TEST_REP_VAR }}
  TEST_VAR2: IN ACTION
  
jobs:
  Deploy-environment-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Env variables"
        run: |
         echo "Value of variables is ${{ vars.TEST_ENV }}"
         echo "      of variables is ${{ env.TEST_REP_VAR }}"
         echo "second of variables is ${{ env.TEST_VAR2 }}"
