name: TestDeploy
on: 
  push: 
    branches: [ develop, qa, main ] # develop
env:
  env_var: ${{ vars.TEST_ENV }}
  TEST_VAR2: IN_ACTION
  
jobs:
  Deploy-environment-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Env variables"
        run: |
         echo "Value of variables is $env_var"
         echo "second of variables is ${{ env.TEST_VAR2 }}"
