name: TestDeploy25
on: 
  push: 
    branches: [ main, qa, develop]
env:
  environment: ${{ inputs.environment }}
  URL_VAL: ${{ vars.MY_VAR }}
  #TEST: ${{ env.ENV_TEST }}
jobs:
  Deploy-environment-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Env variables"
        run: |
         echo "Value of variables is ${{ env.environment }} ..."
         echo "      of variables is  ${{ env.MY_VAR }} ..."
         echo "second of variables is  $TEST ..."
