name: TestDeploy
on: 
  push: 
    branches: [ develop, qa, main ] # develop
env:
  TEST_ENV_VAR: ${{ vars.TEST_ENV }}
  
jobs:
  Deploy-environment-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Env variables"
        run: echo "Value of variables is $TEST_ENV_VAR"
