name: TestDeploy25
on: 
  push: 
    branches: [ main, qa, develop]
env:
 GET_ENV: ${{ github.ref }}
 URL: ${{ vars.MY_VAR }} 

jobs:
  Deploy-environment-test:
    runs-on: ubuntu-latest
    environment: ${{ github.ref }}
    steps:
      - name: "Say Hello Env variables"
        run: |
         echo "Value of variables is ${{ env.GET_ENV }} ..."
         echo "      of variables is  ${{ vars.MY_VAR }} ..."
         echo "second of variables is  $TEST ..."
         echo "theerth of var is  ${{ env.URL }} ..."
