name: TestDeploy25
on: 
  push: 
    branches: [ main, qa, develop]
env: 
  URL_VAL: '${{ vars.TEST_ENV }}'
jobs:
  Deploy-environment-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Env variables"
        run: |
         echo "Value of variables is ${{ env.URL_VAL }} ..."
         echo "      of variables is $URL_VAL ..."
         echo "second of variables is  ${{ secrets.URL }} ..."
